version: '3'

networks:
  frontend:
    external:
      name: app_frontend
  backend:
    external:
      name: app_backend

services:
  mysql:
    image: mysql:5.7.29
    container_name: mysql5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "GXDzKBt85Le7Pew1"

    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis
    container_name: redis
    restart: always
    command: --appendonly yes
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    networks:
      - backend