version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  docker-data-path:
    driver: ${VOLUMES_DRIVER}

services:

  php-fpm:
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=7.3
        - INSTALL_SOCKETS=true
        - INSTALL_GD=true
        - INSTALL_GMP=false
        - INSTALL_REDIS=true
        - INSTALL_PCNTL=true
        - INSTALL_SWOOLE=false
    volumes:
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
    ports:
      - "9000"
    stdin_open: true
    tty: true
    networks:
      - backend

  
  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl

    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"

    stdin_open: true
    tty: true
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend