version: '3'

volumes:
  docker-data-path:
    driver: ${VOLUMES_DRIVER}

networks:
  backend:
    driver: bridge

services:
  php-fpm:
    image: registry.cn-shanghai.aliyuncs.com/xingshun/php:${PHP_VERSION}-fpm-alpine-event
    volumes:
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
    expose:
      - "9000"
    # network_mode: "host"
    networks:
      - backend
    command: ["php-fpm"]

  nginx:
    image: registry.cn-shanghai.aliyuncs.com/xingshun/nginx:1.17.9
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    # network_mode: "host"
    networks:
      - backend
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php-fpm

    