version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  mysql:
    image: mysql:5.7.29
    container_name: mysql5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis
    container_name: redis
    restart: always
    # command: --appendonly yes
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    networks:
      - backend

  php7.2:
    image: hyperf/hyperf:7.2-alpine-v3.9-cli

    # restart: always
    ports:
      - "9501:9501"
    volumes:
      - ${APP_PATH}:/hyperf-skeleton
    depends_on:
      - mysql
      - redis
    working_dir: "/hyperf-skeleton"
    networks:
      - backend
      - frontend
    entrypoint: /bin/sh
    stdin_open: true
    tty: true

